### ISSUE TITLE
Describe scenarios for role Tenant

### ISSUE THREAD

**Issue by EvgenyDementev** [Eugen1204/SearchYourHome#2]
Describe scenarios for role Tenant
- Search daily
  - open search page
  - select city, dates, price range, ...
  - press search button
  - system show available apartments
  - user select apartment
  - system show current apartment (scenario)

- Search long term
- System show current apartment 
  - photos
    - ...
- Book apartment
- Give feedback 
-

**Comment by Eugen1204** [comment]
Search daily

     open search page
     select city, dates, price range, ...
     press search button
     system show available apartments
     user select apartment
     system show current apartment (scenario)
Search long term

System show current apartment

      photos
      description
      show contacts
      back
Book apartment

Give feedback

My profile
     login
     password
     account login

my announcements
     add
     add photo
     add describe
     add price
     add adress
     add tel number
     add announcements

registration
     email or num phone
     password
     confirm password
     complite registration
