### ISSUE TITLE
Draw user interface for Tenant scenarios

### ISSUE THREAD

**Issue by EvgenyDementev** [Eugen1204/SearchYourHome#6]
Draw user interface for Tenant scenarios

**Comment by Eugen1204** [comment]
![_профиль](https://github.com/Eugen1204/SearchYourHome/assets/136818072/f71033bf-619a-4504-82e3-78d1b864f94e)

**Comment by Eugen1204** [comment]
https://github.com/Eugen1204/SearchYourHome/wiki/draw-tenant-interface
